const SYNC_STATE_BOOTSTRAP = 'BOOTSTRAP'
const SYNC_STATE_CATCHUP = 'CATCHUP'
const SYNC_STATE_OFFLINE = 'OFFLINE'
const SYNC_STATE_SYNCED = 'SYNCED'
const SYNC_STATE_CONNECTING = 'CONNECTING'
const SYNC_STATE_UNKNOWN = 'UNKNOWN'

module.exports = {
    SYNC_STATE_CONNECTING,
    SYNC_STATE_OFFLINE,
    SYNC_STATE_CATCHUP,
    SYNC_STATE_BOOTSTRAP,
    SYNC_STATE_SYNCED,
    SYNC_STATE_UNKNOWN
}